"""
src/params_io.py
================

Writes `params.xlsx` and the Markdown parameter reference from the values in
`src/params_schema.py`.

One direction only: code -> spreadsheet. The spreadsheet is a readable register
of what is set, never a source of values, so editing it changes nothing. Change
`src/params_schema.py` and run `00_parameters.py`.

Kept apart from `params_schema.py` so that the schema stays free of I/O, and
out of `00_parameters.py`, whose leading digits make it unimportable.
"""
from __future__ import annotations

from typing import Any

import pandas as pd

from src.params_schema import Params, flatten

PARAMS_FILE = 'params.xlsx'
SHEET = 'parameters'


def save(params: Params, path: str = PARAMS_FILE) -> pd.DataFrame:
    """Write the register: one row per parameter, name/description/key/value."""
    frame = pd.DataFrame(flatten(params), columns=['name', 'description', 'key', 'value'])
    with pd.ExcelWriter(path, engine='openpyxl') as writer:
        frame.to_excel(writer, sheet_name=SHEET, index=False)
        _widen(writer.sheets[SHEET], frame)
    return frame


def _widen(sheet: Any, frame: pd.DataFrame) -> None:
    """Column widths, so the file is readable the moment it is opened."""
    for index, width in enumerate((24, 96, 30, 34), start=1):
        sheet.column_dimensions[chr(64 + index)].width = width
    sheet.freeze_panes = 'A2'


def reference(params: Params) -> str:
    """The same content as Markdown, for documentation/PARAMETER_REFERENCE.md."""
    lines = [
        '# Parameter reference',
        '',
        'Generated by `00_parameters.py` from `src/params_schema.py` -- do not',
        'edit this file, and do not edit `params.xlsx`. Both are outputs.',
        '',
        '**To change a parameter, edit `src/params_schema.py`** and run:',
        '',
        '```bash',
        './.venv/bin/python 00_parameters.py',
        '```',
        '',
    ]
    current_section = None
    for _, description, key, value in flatten(params):
        section = key.split('.')[0]
        if section != current_section:
            current_section = section
            lines += ['', f'## `{section}`', '',
                      '| Parameter | Value | What it does |',
                      '|---|---|---|']
        lines.append(f'| `{key}` | `{value}` | {description} |')
    lines.append('')
    return '\n'.join(lines)
